/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|


 * DO NOT EDIT THIS FILE!!
 *
 *  TO CUSTOMIZE ProjectApprovalBase PLEASE EDIT ../project-approval.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */

/**
 * This is the model of ProjectApproval object
 *
 */
export class ProjectApprovalBase {

    constructor() { }

    public _id: string;
    public CreatedById?: number;
    public CreatedOn?: Date;
    public IsActive?: Boolean;
    public Level?: number;
    public ModifiedById?: number;
    public ModifiedOn?: Date;
    public ProjectId?: number;
    public UserId?: number;
    public UserTypeId?: number;
    public VendorId?: number;
}
