/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE projectBaseService PLEASE EDIT ../project.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Project } from '../../domain/test2_db/project';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../Project.service.ts
 */

/*
 * SCHEMA DB Project
 *
	{
		JsaNo: {
			type: 'String'
		},
		ProjectCode: {
			type: 'String'
		},
		ProjectName: {
			type: 'String'
		},
		StatusId: {
			type: 'Boolean'
		},
		VendorId: {
			type: 'Integer'
		},
		//RELATIONS
		//EXTERNAL RELATIONS
	}
 *
 */
@Injectable()
export class ProjectBaseService {

    contextUrl: string = environment.endpoint + '/projects';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * ProjectService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Project): Observable<Project> {
        return this.http
            .post<Project>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * ProjectService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * ProjectService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id 
    *
    */
    get(id: string): Observable<Project> {
        return this.http
            .get<Project>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * ProjectService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Project[]> {
        return this.http
            .get<Project[]>(this.contextUrl)
            .pipe(map(data => data));
    }

    /**
    * ProjectService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(item: Project): Observable<Project> {
        return this.http
            .post<Project>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs

}
