/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE project-approvalBaseService PLEASE EDIT ../project-approval.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { ProjectApproval } from '../../domain/test2_db/project-approval';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../ProjectApproval.service.ts
 */

/*
 * SCHEMA DB ProjectApproval
 *
	{
		CreatedById: {
			type: 'Integer'
		},
		CreatedOn: {
			type: 'Date'
		},
		IsActive: {
			type: 'Boolean'
		},
		Level: {
			type: 'Integer'
		},
		ModifiedById: {
			type: 'Integer'
		},
		ModifiedOn: {
			type: 'Date'
		},
		ProjectId: {
			type: 'Integer'
		},
		UserId: {
			type: 'Integer'
		},
		UserTypeId: {
			type: 'Integer'
		},
		VendorId: {
			type: 'Integer'
		},
		//RELATIONS
		//EXTERNAL RELATIONS
	}
 *
 */
@Injectable()
export class ProjectApprovalBaseService {

    contextUrl: string = environment.endpoint + '/projectapprovals';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * ProjectApprovalService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: ProjectApproval): Observable<ProjectApproval> {
        return this.http
            .post<ProjectApproval>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * ProjectApprovalService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * ProjectApprovalService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id 
    *
    */
    get(id: string): Observable<ProjectApproval> {
        return this.http
            .get<ProjectApproval>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * ProjectApprovalService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<ProjectApproval[]> {
        return this.http
            .get<ProjectApproval[]>(this.contextUrl)
            .pipe(map(data => data));
    }

    /**
    * ProjectApprovalService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(item: ProjectApproval): Observable<ProjectApproval> {
        return this.http
            .post<ProjectApproval>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs

}
